### ISSUE TITLE
IDEA or BUG ? on (Begin querying the model on a given connection) not work 

### ISSUE THREAD

**Issue by abkrim** [pdphilip/laravel-elasticsearch-tests#1]
Hello

Maybe the title is not entirely correct, even though I try it in several ways.

By necessity and because sometimes it is very good to work from a local point on remote connections (production), I am usually a user of Eloquent's 'on' method.

```php
$count = WorkAnalyzer::on('elasticsearch_production')->count();

ray($count)
```

Today there was one of those cases in which in my `WorkAnalyzer` model I wanted to have in a command the possibility of choosing my connection to work on the connection in production, a question.

And to always test that it is working, I usually do a count.

My surprise is that it gave me the coneo data, from the local installation.

Also try

```php
$workAnalyzer = new WorkAnalyzer();
$workAnalyzer->setConnection('elasticsearch_production');

$count = $workAnalyzer->count();
ray($count);
```

But the result was the same.

Of course, check the values of the database connection called `elasticsearch_production` with a config('database.elasticsearch_production')

```php
array:11 [▶
  "driver" => "elasticsearch"
  "auth_type" => "http"
  "hosts" => array:1 [▶
    0 => "https://remote:address:9200"
  ]
  "username" => "elastic"
  "password" => "wicmJOJOJOJOJO5t8k"
  "cloud_id" => ""
  "api_id" => ""
  "api_key" => ""
  "ssl_cert" => "/Users/user/Sites/sitelight/ssl/http_ca_local.crt"
  "index_prefix" => ""
  "query_log" => array:2 [▶
    "index" => "laravel_query_logs"
    "error_only" => true
  ]
]```


All the best

**Comment by pdphilip** [comment]
Hey @abkrim - I'll have a look at this when I get a gap

**Comment by pdphilip** [comment]
Hi @abkrim - the package has been upgraded to cater for this, see: https://github.com/pdphilip/laravel-elasticsearch/releases/tag/v4.0.2

All the best
